### ISSUE TITLE
1.1-Live_templates: Problem with #7: "In C# 2.0+ where type member declaration is allowed"

### ISSUE THREAD

**Issue by TobiasWehrum** [JetBrains/resharper-rider-samples#3]
Using VS2015/Resharper: When I create the live template as described at 7., I can't use it at the 7. "^ here", but it does work at the 6. "^ here". Only when I select "where namespace declaration is allowed" I can invoke it at the 7. "^ here".

**Comment by maartenba** [comment]
Added a few additional comments in the exercise. Do make sure to sure the `tf` template before the last `}` in the file, which is probably the reason you had to select "where namespace declaration is allowed".
