### ISSUE TITLE
Proposal for improvement of "3.1-Navigate_back.cs"

### ISSUE THREAD

**Issue by sun-flat-yamada** [JetBrains/resharper-rider-samples#31]
# Summary

- "3.1-Navigate_back.cs" is a workshop for "BACK" navigation.
- However, We are usually familiar with "BACK" and "FORWARD".
- So, I propose that this workshop be improved to include both "BACK" and "FORWARD" operations.

Are you sure you want to make this change @maartenba ?

# Specific proposed changes

There are two changes :

1. Rename filename (include both "back" and "forward" operations)
2. Add content for a workshop on "FORWARD.

```
01-Navigation\3-Navigate_to_somewhere_youve_already_been\3.1-Navigate_back.cs
  -> 3.1-Navigate_back_and_forward.cs
```

# Related issues

https://github.com/JetBrains/resharper-rider-samples/issues/20
Proposal for creating a Japanese localized version

**Comment by maartenba** [comment]
Totally fine with this change, yes. Thanks!

**Comment by sun-flat-yamada** [comment]
@maartenba , I'm done.

Could you please check?
And if it is OK, please close this issue.

Thanks.
