### ISSUE TITLE
Update JetBrains configuration files

### ISSUE THREAD

**Issue by sun-flat-yamada** [JetBrains/resharper-rider-samples#34]
# NOTE

- This issue has undergone changes to the proposal during the discussion process.
- I note that the `title and summary have been updated` to reflect what I expect them to say so as not to give incorrect information when referred to later.
- If you want to see the original process, check the record.

# Summary

- When I clone this workshop repository and open it with Rider, the personal configuration file of Rider is detected as a change.
- In my environment, the following appears in the diff (@Rider 2021.1.2).

```
        .idea/.idea.resharper-rider-samples/.idea/.gitignore
        .idea/.idea.resharper-rider-samples/.idea/.name
        .idea/.idea.resharper-rider-samples/.idea/encodings.xml
        .idea/.idea.resharper-rider-samples/.idea/indexLayout.xml
        .idea/.idea.resharper-rider-samples/.idea/vcs.xml
```

# Proposed improvement

- Add all project configuration recorded by the latest Rider (2021.1.2) to the repository.

(Initially, I thought that it was a personal setting that should not be included in the repository and I thought to add it to ".gitignore", but I was wrong; the update of Rider increased the number of configuration files, but it was not reflected in the repository.)

The following describes the idea of sharing the configurations:
https://www.jetbrains.com/help/idea/creating-and-managing-projects.html#share-project-through-vcs

# Related issues

https://github.com/JetBrains/resharper-rider-samples/issues/20
Proposal for creating a Japanese localized version

**Comment by maartenba** [comment]
@sun-flat-yamada Absolutely, please go ahead and add these entries to `.gitignore`

**Comment by sun-flat-yamada** [comment]
Hi, @maartenba .

I have a consultation.

# What's a best practice on sharing jetbrains configuration?

Jetbrains ide saves configuration into ".idea" directory and we can share project configuration.
However, some configuration can modify by each of the project member easily.

In fact, just by cloning this workshop and opening it with Rider, I have detect changes in my personal configurations.

I believe that configuration files that can be easily changed depending on individual environments and preferences should not be included in the repository management.

But at the JetBrains reference page, you will see that only some of the files in the ".idea" directory are excluded.

https://www.jetbrains.com/help/idea/creating-and-managing-projects.html#share-project-through-vcs

What do you think about this case?
If you, as JetBrains, were to teach a new user only one best method, what would it be?

**Comment by maartenba** [comment]
@sun-flat-yamada The reference page is mostly correct, I believe for Rider the recommended way is to now place this in `.idea/.idea.xxxxxxx/.idea/.gitignore`. For the localized version, you can add the below entires into `localized/jp/.idea/.idea.resharper-rider-samples/.idea/.gitignore`. Some files can be added to VCS, and others will be ignored by this file.

```
# Default ignored files
/shelf/
/workspace.xml
# Rider ignored files
/modules.xml
/.idea.JetBrains.Space.iml
/contentModel.xml
/projectSettingsUpdater.xml
/dataSources.local.xml
# Editor-based HTTP Client requests
/httpRequests/
/aws.xml
```

**Comment by sun-flat-yamada** [comment]
@maartenba I see.

If what you say is best, then I think this repository has one of the following problems.

a. There is a problem with current repository. The file in this case, which is detected as a change in my environment, is lack from the repository registration.

b. There is a problem with Rider (IDE). The personal configuration file is not saved in the directory where it should be excluded.


Because, as I explained above, I just cloned this repository and opened it, but git detected the changes.

I'm beginning to think that the addition to "ignore" as originally proposed is inappropriate.
Could you give me your perspective on this?

**Comment by maartenba** [comment]
Let me see if I can update the repository and check. Do know that Rider may sometimes upgrade some of the committed files, which could be what you are seeing. Regardless, let me check.

**Comment by maartenba** [comment]
Pushed an update - if you see any more files in `.idea` that are being edited please let me know - the current set is nice to share and be part of Git.

**Comment by sun-flat-yamada** [comment]
Hi, @maartenba .

Thank you for your quick adoption.

I checked out HEAD, and I detect only one change :

```
    .idea/.idea.resharper-rider-samples/.idea/.name
```

My work place is renaming the checkout directory, so I think JetBrains will create a `.name` file.

**Comment by maartenba** [comment]
If you get a fresh version, what files do you see that Rider changes/wants to commit?

**Comment by sun-flat-yamada** [comment]
@maartenba 
> If you get a fresh version, what files do you see that Rider changes/wants to commit?

It is the following :

```
(root = resharper-rider-samples) .idea/.idea.resharper-rider-samples/.idea/.name
```

The following files are registered, but the files on the root side are not registered.
localized/en/.idea 

```
.idea/.idea.resharper-rider-samples/.idea/.name <- Not Exists
localized/ja/.idea/.idea.resharper-rider-samples/.idea/.name <- Exists
```

**Comment by maartenba** [comment]
That can be committed I believe, feel free to add it.

**Comment by sun-flat-yamada** [comment]
@maartenba , OK I will update it.

And I have updated the title and summary of this issue, so that people won't refer to the wrong information later.

**Comment by maartenba** [comment]
Thanks @sun-flat-yamada !
