### ISSUE TITLE
Prevent adding invalid windows filenames

### ISSUE THREAD

**Issue by ststeiger** [JetBrains/resharper-rider-samples#7]
When I am on Linux, I can add files like "List?Trigger.sql". 
This should actually be List_Trigger.sql, the "? to _ mixup" comes from keyboard-layout mixup. 
When I commit changes to the git repo on Linux, this works. 
When I want to pull the latest version from the git repo on Windows, this creates errors. 

Rider should warn on pushing illegal windows filenames to a git repo.

**Comment by ForNeVeR** [comment]
@ststeiger, thanks for feedback. Could you please file this issue at https://youtrack.jetbrains.com/ ?

**Comment by maartenba** [comment]
Going to close the issue in this repo for now.
